/**
 * Emit the built client bundle as a TypeScript string the game page can inline.
 * Run through `npm run build:client -w web`, which builds the IIFE first; the
 * generated module is committed so tests, typecheck, and `npm run dev` never
 * need a build step.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { sourcesFingerprint } from './client-fingerprint.js';

const here = dirname(fileURLToPath(import.meta.url));
const built = readFileSync(join(here, '..', 'dist-client', 'client.js'), 'utf8').trim();

// The bundle is inlined between <script> tags, so a closing tag inside it would
// end the script early. Nothing in the sources writes one; refuse if that changes.
if (built.includes('</script>')) {
  throw new Error('the client bundle contains a closing script tag and cannot be inlined');
}

const module = `// Generated by \`npm run build:client -w web\` from web/src/client/. Do not edit.
// The shell inlines this for pages that ask for it (ADR-0006/ADR-0007): this
// deployment serves no static files (ADR-0002), so the bundle travels inside the
// HTML rather than as its own request.

export const CLIENT_SCRIPT = ${JSON.stringify(built)};

/** The sources this bundle was built from; a test fails when they drift. */
export const CLIENT_SCRIPT_SOURCES = ${JSON.stringify(sourcesFingerprint())};
`;

const target = join(here, '..', 'src', 'client-script.generated.ts');
writeFileSync(target, module);
console.log(`wrote ${target} (${built.length} bytes of script)`);
